running src/format.py
Beginning import_data from file(s): input/investigators_export.xlsx
Data shape = 204715 rows, 12 columns
LOG_NO -> cr_id , INVST_LAST_NAME -> last_name , INVST_FIRST_NAME -> first_name , MIDDLE_INITIAL -> middle_initial , STAR -> star , SEX -> gender , RACE -> race , BIRTH_YEAR -> birth_year , APPOINTED_DATE -> appointed_date , CURRENT_UNIT_ASSNMNT -> current_unit , INVESTIGATOR_TYPE -> investigator_type , ASSIGN_DATETIME -> assigned_date
ROWID column inserted
Column 'ROWID' was not cleaned.
Column 'cr_id' was not cleaned.
Column 'star' cleaned as star using GeneralCleaners.
Column 'gender' cleaned as gender using GeneralCleaners.
[nan, 'X'] values not in gender_types.yaml file. 40150 cases replaced with 'nan'
Column 'race' cleaned as race using GeneralCleaners.
[nan, 'U'] values not in race_types.yaml file. 40570 cases replaced with 'nan'
Column 'birth_year' cleaned as int using GeneralCleaners.
Column 'appointed_date' cleaned as date using DateTimeCleaners.
Column 'current_unit' cleaned as int using GeneralCleaners.
Column 'investigator_type' was not cleaned.
Column 'assigned_date' cleaned as date using DateTimeCleaners.
Column(s) '('last_name', 'first_name', 'middle_initial')' cleaned as name(s) using NameCleaners.
Columns dropped due to all NA values: ('middle_name', 'second_name', 'human_name', 'full_name')
16 resolved conflicts. 0 unresolved conflicts
Total rows: 204715
Unique id + conflict rows: 3372
Conflict rows: 16
Resolved conflcit UID count: 11
Total unique ids: 3367.0

Writing data with 204715 rows to output/complaints-investigators_2000-2018_2018-07.csv.gz with 3367 unique UIDs
